services:
  windows:
    image: dockurr/windows
    container_name: windows
    networks:
      BcContainerNetwork:
        ipv4_address: 172.20.0.100
    environment:
      VERSION: "25"
      # EDITION: "core"
      REGION: "de-DE"
      KEYBOARD: "de-DE"
      RAM_SIZE: "16G"
      CPU_CORES: "12"
      DISK_SIZE: "64G"
      USERNAME: "adigo"
      PASSWORD: "adigo"
      VMX: "Y"
      ARGUMENTS: "-cpu host,hypervisor=off,vmx=on,mpx=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=whatever,-tsc-deadline,-x2apic"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 7048:7048
      - 7047:7047
      - 7049:7049
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./storage:/storage
      - ./data-exchange:/data
      - ./startup-scripts:/oem
    privileged: true
    restart: unless-stopped
    stop_grace_period: 2m

networks:
  BcContainerNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
